#!/usr/bin/env python3
#
# customize-night-green.py
#
# Post-processes profile-3d-contrib/profile-night-green.svg generated by the
# yoshi389111/github-profile-3d-contrib action so it visually fits a GitHub
# profile README:
#
#   1. Background recolor: #00000f (template default) -> #0d1117 (GitHub dark)
#   2. Removes the bottom-strip stars + forks icons + counts
#
# Coordinates (608/736/802/650/772/830) come from the upstream layout template
# and are stable regardless of stat magnitude (verified against the project's
# own demo SVG with 135 stars / 14 forks).

import re
import sys
from pathlib import Path

SVG_PATH = Path(__file__).resolve().parent.parent / "profile-3d-contrib" / "profile-night-green.svg"

# anchor regex on the icon's <g translate(...)> wrapper because that's the
# stable hook; lazy .*? is bounded by </g> and the immediately-following <text>
STAR_GROUP = re.compile(
    r'<g transform="translate\(608,\s*802\)[^"]*"[^>]*>.*?</g>'
    r'\s*<text[^>]*x="650"[^>]*y="830"[^>]*>.*?</text>',
    re.DOTALL,
)
FORK_GROUP = re.compile(
    r'<g transform="translate\(736,\s*802\)[^"]*"[^>]*>.*?</g>'
    r'\s*<text[^>]*x="772"[^>]*y="830"[^>]*>.*?</text>',
    re.DOTALL,
)


def main() -> int:
    with open(SVG_PATH, encoding="utf-8") as f:
        data = f.read()
    before = len(data)
    is_fresh = "#00000f" in data

    data = data.replace("#00000f", "#0d1117")
    data, n_star = STAR_GROUP.subn("", data)
    data, n_fork = FORK_GROUP.subn("", data)

    with open(SVG_PATH, "w", encoding="utf-8") as f:
        f.write(data)

    print(
        f"customized {SVG_PATH}: {before} -> {len(data)} bytes "
        f"(fresh={is_fresh}, stars removed={n_star}, forks removed={n_fork})"
    )
    if is_fresh and (n_star == 0 or n_fork == 0):
        print(
            "WARNING: fresh SVG didn't match expected layout markers; "
            "upstream github-profile-3d-contrib may have changed coordinates",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
